spring:
  application:
    name: service-discovery
server:
  port: 8761
  forward-headers-strategy: framework
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka/

