server:
  port: 1111

spring:
  application:
    name: productservice
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/product-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#        show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG


---
spring:
  config:
    activate:
      on-profile: "local"
  cloud:
    discovery:
      client:
        simple: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
---
spring:
  config:
    activate:
      on-profile: "kubernetes"
  cloud:
    discovery:
      client:
        simple: true
