spring:
  cloud:
    kubernetes:
      config:
        trust-store: /home/application/microservice/ca.crt
        trust-store-password: changeit
      enabled: true
    discovery:
      client:
        config:
          enabled: true
      ribbon:
        enabled: true


eureka:
  client:
    enabled: false
