server:
  port: 1113
spring:
  application:
    name: userservice
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/user-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


---
spring:
  config:
    activate:
      on-profile: "local"
  cloud:
    discovery:
      client:
        simple: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
---
spring:
  config:
    activate:
      on-profile: "kubernetes"
  cloud:
    discovery:
      client:
        simple: true



logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG
    com.ic.userservice: DEBUG
  pattern:
        level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
