server:
  port: 1112
spring:
  application:
    name: authservice
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]
---
spring:
  config:
    activate:
      on-profile: "local"
  cloud:
    discovery:
      client:
        simple: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
---
spring:
  config:
    activate:
      on-profile: "kubernetes"
  cloud:
    discovery:
      client:
        simple: true


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG
    com.ic.authservice: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"